name: Validate Altered Knowledge Base

on:
  push:
    branches: [ main, master ]
    paths:
      - "CARDS/**"
      - "COLLECTION/**"
      - "RULES/**"
      - "HISTORY/**"
      - "DECKS/**"
      - "UTILS/**"
      - "manifest.json"
  pull_request:
    branches: [ main, master ]
    paths:
      - "CARDS/**"
      - "COLLECTION/**"
      - "RULES/**"
      - "HISTORY/**"
      - "DECKS/**"
      - "UTILS/**"
      - "manifest.json"
  workflow_dispatch:

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Repo validation (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # optional: install dependencies if du mal welche hast
      - name: Install deps (optional)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run validator (normal mode)
        run: |
          python UTILS/validate_repo.py

      # optionaler “strenger” Lauf: warnt dich, wenn du willst, dass Warnungen als Fehler gelten
      - name: Run validator (strict mode)
        if: ${{ always() }}  # wird auch ausgeführt, wenn der vorige Step fehlschlug; nimm 'if: success()' falls du es anders willst
        run: |
          python UTILS/validate_repo.py --strict
